### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.transform#128]
Documentation issues noted as part of #125 but are quite involved.

- A number of examples use `:::`. We shouldn't use this.
- `merge_expression_module` and `merge_expression_srv` use chunks.

**Comment by donyunardi** [comment]
I feel that the points that you made can be split into two issues.

> merge_expression_module and merge_expression_srv use chunks.

Lets handle this part with insightsengineering/teal.transform/issues/129

As for this
> A number of examples use :::. We shouldn't use this.

Let's discuss this with the team first and come to an agreement since teal.transform is not only place that I see this happening, mostly internal functions.
Adding this topic to insightsengineering/nestdevs-tasks/issues/17 first.

**Comment by donyunardi** [comment]
Topics are addressed or handled in other issue for efficiency.
Closing.
